name: 'uk_online_retail'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  uk_online_retail:
    +materialized: view
    +location: EU

    staging:
      +materialized: view
      +location: EU

    intermediate:
      +materialized: table
      +location: EU

    marts:
      +materialized: table
      +location: EU
