sources:
  - name: raw
    schema: uk_online_retail
    tables:
      - name: online_retail
        identifier: uk_online


models:
  - name: customer_sales_mart
    description: "Müşteri bazlı özet, RFM analizi için"
    columns:
      - name: CustomerID
        description: "Müşteri ID"
        tests:
          - not_null
          - unique
      - name: Frequency
        tests:
          - not_null
      - name: Monetary
        tests:
          - not_null
      - name: LastPurchaseDate
        tests:
          - not_null
      - name: Recency
        tests:
          - not_null
          - expression_is_true:
              expression: "Recency >= 0"
